pipeline {
    agent any
    tools {
        nodejs '19.2.0'
    }
    stages {
        stage('Build') { 
            steps {
                withNPM(npmrcConfig:'my-custom-npmrc') {
                    echo "Performing npm build..."
                    sh 'npm install'
                }
            }
        }
    }

    post {
        success {
            echo "SUCCESSFUL"
        }
        failure {
            echo "FAILED"
        }
    }
}