pipeline {
    agent any
    tools {
        nodejs '19.2.0'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm login'
                sh 'npm install'
            }
        }
    }

    post {
        success {
            echo "SUCCESSFUL"
        }
        failure {
            echo "FAILED"
        }
    }
}